# Generated by Django 3.0.6 on 2020-06-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followed_id',
            new_name='followed',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower_id',
            new_name='follower',
        ),
    ]
