# Generated by Django 3.0.6 on 2020-06-06 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200606_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followed',
            new_name='followed_id',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='follower_id',
        ),
    ]
