# Generated by Django 3.0.6 on 2020-07-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200620_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_profile.jpg', upload_to='profile_pics', verbose_name='Upload Photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phonenum',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
    ]
