# Generated by Django 3.0.6 on 2020-06-06 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='feed_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_likes', to='feed.Feed'),
        ),
        migrations.AlterField(
            model_name='like',
            name='liker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
