# Generated by Django 3.0.6 on 2020-06-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20200606_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
