# Generated by Django 3.0.6 on 2020-06-11 10:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0004_feed_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=100)),
                ('date_commented', models.DateTimeField(default=datetime.datetime.now)),
                ('commentor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
                ('feed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_comments', to='feed.Feed')),
            ],
        ),
    ]
