# Generated by Django 3.0.6 on 2020-06-13 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
