# Generated by Django 3.0.6 on 2020-06-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_feed_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='video',
            field=models.FileField(null=True, upload_to='post_videos'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
    ]
