# Generated by Django 3.0.6 on 2020-06-17 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20200615_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='post_images')),
                ('feed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='feed.Feed')),
            ],
        ),
    ]
