# Generated by Django 3.0.6 on 2020-06-17 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_auto_20200617_0521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='images',
            new_name='gallery',
        ),
    ]
