# Generated by Django 3.0.6 on 2020-06-18 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_auto_20200617_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='comment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='feed.Comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='feed_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_likes', to='feed.Feed'),
        ),
    ]
