# Generated by Django 3.0.6 on 2020-06-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='status',
        ),
    ]
