# Generated by Django 3.0.6 on 2020-06-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_remove_tag_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
