# Generated by Django 3.0.6 on 2020-07-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='caption',
            field=models.CharField(max_length=30, verbose_name='Caption'),
        ),
    ]
